[[main]]
name = "Produkt"
url = "/produkt"
weight = 10
[[main]]
name = "Unternehmen"
url = "/unternehmen"
weight = 20
[[main]]
name = "Service & News"
url = "/service-news"
weight = 30

[[main]]
parent = "Produkt"
name = "Anwendung"
title = "Wie das Pressstanzwerkzeug funktioniert"
url = "/produkt/anwendung"
weight = 10
[[main]]
parent = "Produkt"
name = "Technische Daten"
title = "Welche Voraussetzungen sind notwendig?"
url = "/produkt/technische-daten"
weight = 20
# [[main]]
# parent = "Produkt"
# name = "Ausschreibung"
# title = "Texte um Ihre Ausschreibung zu optimieren"
# url = "/produkt/ausschreibungstexte"
# weight = 30
[[main]]
parent = "Produkt"
name = "FAQs"
title = "Wissenswertes rund um PRESSSTA"
url = "/produkt/faqs"
weight = 40
[[main]]
parent = "Produkt"
name = "Bezugsquellen"
title = "Wo man PRESSSTA kaufen oder auch leihen kann"
url = "/produkt/bezugsquellen"
weight = 50
[[main]]
parent = "Produkt"
name = "Anfrage / Bestellung"
title = "Das Formular zum Produkt"
url = "/produkt/anfrage-bestellung"
weight = 60


[[main]]
parent = "Unternehmen"
name = "Philosophie"
title = "Was treibt uns an?"
url = "/unternehmen/philosophie"
weight = 20
#[[main]]
#parent = "Unternehmen"
#name = "Sitemap"
#title = "Alle Seiten im Überblick"
#url = "/sitemap.xml"
#weight = 53
[[main]]
parent = "Unternehmen"
name = "Erfinder"
title = "Wer hat's erfunden?"
url = "/unternehmen/erfinder"
weight = 40
[[main]]
parent = "Unternehmen"
name = "Kontakt"
title = "get in Touch"
url = "/unternehmen/kontakt"
weight = 50
[[main]]
parent = "Unternehmen"
name = "Datenschutz"
title = "ist uns ein großes Anliegen"
url = "/unternehmen/datenschutz"
weight = 55
[[main]]
parent = "Unternehmen"
name = "Impressum"
title = "alle Fakten"
url = "/unternehmen/impressum"
weight = 60

[[main]]
parent = "Service & News"
name = "News"
title = "Neues, interessantes & lesenswertes"
url = "/service-news/news"
weight = 10
# [[main]]
# parent = "Service & News"
# name = "Presse"
# title = "Berichte aus Presse und anderen Medien"
# url = "/service-news/presse"
# weight = 20
# [[main]]
# parent = "Service & News"
# name = "Zeitschriften"
# title = "Welche Magazine sich mit unserem Fach beschäftigen"
# url = "/service-news/zeitschriften"
# weight = 30
[[main]]
parent = "Service & News"
name = "Downloads"
title = "Produktinfos, techn. Daten etc."
url = "/service-news/downloads"
weight = 30


[[action]]
name = "Partner finden!"
url = "/produkt/bezugsquellen"




[[footer1]]
name = "Unternehmen"
url = "/unternehmen/philosophie"
weight = 10
[[footer1]]
name = "Datenschutz"
url = "/unternehmen/datenschutz"
weight = 20
[[footer1]]
name = "Impressum"
url = "/unternehmen/impressum"
weight = 30
[[footer1]]
name = "AGB"
url = "/unternehmen/agb"
weight = 40

[[footer2]]
name = "Produkt"
url = "/produkt/anwendung"
weight = 50
[[footer2]]
name = "technische Daten"
url = "/produkt/technische-daten"
weight = 60
[[footer2]]
name = "Presse"
url = "/service-news/presse"
weight = 70
[[footer2]]
name = "Bezugsquellen"
url = "/produkt/bezugsquellen"
weight = 80


[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/TODO"
weight = 10
[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://facebook.com/TODO"
weight = 10
[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://youtube.com/TODO"
weight = 10



# [[main]]
# title = "RSS"
# url = "/index.xml"
# weight = 4