[[main]]
name = "Produkt"
url = "/produkt"
weight = 10
[[main]]
name = "Unternehmen"
url = "/unternehmen"
weight = 20
[[main]]
name = "Service & News"
url = "/service-news"
weight = 30

[[main]]
parent = "Produkt"
name = "Ausschreibungstexte"
title = "Ich bin eine Navigationsbeschreibung"
url = "/produkt/ausschreibungstexte"
weight = 10
[[main]]
parent = "Produkt"
name = "Anwendung"
title = "Ich bin eine Navigationsbeschreibung"
url = "/produkt/anwendung"
weight = 20
[[main]]
parent = "Produkt"
name = "FAQs"
title = "Ich bin eine Navigationsbeschreibung"
url = "/produkt/faqs"
weight = 30
[[main]]
parent = "Produkt"
name = "Technische Daten"
title = "Ich bin eine Navigationsbeschreibung"
url = "/produkt/technische-daten"
weight = 40
[[main]]
parent = "Produkt"
name = "Anfrage/Bestellung"
title = "Ich bin eine Navigationsbeschreibung"
url = "/produkt/anfrage-bestellung"
weight = 50
[[main]]
parent = "Produkt"
name = "Bezugsquellen"
title = "Ich bin eine Navigationsbeschreibung"
url = "/produkt/bezugsquellen"
weight = 60

[[main]]
parent = "Unternehmen"
name = "Datenschutz"
title = "Ich bin eine Navigationsbeschreibung"
url = "/unternehmen/datenschutz"
weight = 10
[[main]]
parent = "Unternehmen"
name = "Philosophie"
title = "Ich bin eine Navigationsbeschreibung"
url = "/unternehmen/philosophie"
weight = 20
[[main]]
parent = "Unternehmen"
name = "Sitemap"
title = "Ich bin eine Navigationsbeschreibung"
url = "/unternehmen/sitemap"
weight = 30
[[main]]
parent = "Unternehmen"
name = "Erfinder"
title = "Ich bin eine Navigationsbeschreibung"
url = "/unternehmen/erfinder"
weight = 40
[[main]]
parent = "Unternehmen"
name = "Kontakt"
title = "Ich bin eine Navigationsbeschreibung"
url = "/unternehmen/kontakt"
weight = 50
[[main]]
parent = "Unternehmen"
name = "Impressum"
title = "Ich bin eine Navigationsbeschreibung"
url = "/unternehmen/impressum"
weight = 60

[[main]]
parent = "Service & News"
name = "News"
title = "Neues, interessantes & lesensertes"
url = "/service-news/news"
weight = 10
[[main]]
parent = "Service & News"
name = "Presse"
title = "Berichte aus Presse und anderen Medien"
url = "/service-news/presse"
weight = 20
[[main]]
parent = "Service & News"
name = "Downloads"
title = "Welche Magazine sich mit unserem Fach besch√§ftigen"
url = "/service-news/downloads"
weight = 30




# [[main]]
# title = "RSS"
# url = "/index.xml"
# weight = 4